### ISSUE TITLE
Image caching does not differentiate between different query strings

### ISSUE THREAD

**Issue by BickelLukas** [SixLabors/ImageSharp.Web#331] opened 2023-07-10 12:48 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

3.0.1

### Other Six Labors packages and versions

3.0.1

### Environment (Operating system, version and so on)

Windows 10 x64

### .NET version

7.0

### Description

Our image endpoint is the same for all files and the files are differentiated by a query parameter.
All Images are downloaded at the /attachment/Download endpoint and a `token` query parameter is passed that handels which attachment is downloaded + authentication. 

When caching is turned on all tokens resolve to the same cached image.

Problem is that `ICacheKey` disregards the request query parameters and builds its own query string from the commands. 

### Steps to Reproduce

1. differentiate Images based on query string. 

2. Turn on caching

**Comment by JimBobSquarePants** [comment] 2023-07-11 03:56
By design the library ignores unrecognized query strings when resolving cache version. This prevents DOS attacks by bad actors adding junk to image requests. 

e,g

```
/image.jpeg?width=100&attack=1
/image.jpeg?width=100&attack=2
/image.jpeg?width=100&attack=3
/image.jpeg?width=100&attack=4
/image.jpeg?width=100&attack=5
```

In order to differentiate requests containing that custom value you need to create and register a processor that can recognize the query string parameter. 

An implementation would look like this.

```c#
using System.Globalization;
using Microsoft.Extensions.Logging;
using SixLabors.ImageSharp.Web.Commands;
using SixLabors.ImageSharp.Web.Processors;

namespace YourNamespace;

internal class CustomQuerystringTokenWebProcessor : IImageWebProcessor
{
    public const string Token = "token";

    public IEnumerable<string> Commands { get; } = new[] { Token };

    public FormattedImage Process(FormattedImage image, ILogger logger, CommandCollection commands, CommandParser parser, CultureInfo culture)
        => image;

    public bool RequiresTrueColorPixelFormat(CommandCollection commands, CommandParser parser, CultureInfo culture)
        => false;
}
```

**Closed by JimBobSquarePants** 2023-07-11 03:56 UTC
Labels: needs triage
